[package]
name = "pbt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
geo = "0.29.3"
geo-clipper = "0.8.0"
geo-types = "0.7.14"
indicatif = "0.17.9"
macroquad = "0.4.13"
nalgebra = "0.33.2"
ndarray = "0.16.1"
rayon = "1.10.0"
tobj = "4.0.2"
