# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing
import typing
from enum import Enum, auto

class BinningScheme:
    r"""
    Angular binning scheme for scattering calculations.
    
    Defines how to discretize the scattering sphere into angular bins
    for Mueller matrix and amplitude computations. Supports simple
    regular grids, custom intervals, and arbitrary bin arrangements.
    """
    def __new__(cls,bins:typing.Sequence[typing.Sequence[typing.Sequence[builtins.float]]]): ...
    @staticmethod
    def simple(num_theta:builtins.int, num_phi:builtins.int) -> BinningScheme:
        r"""
        Create a simple binning scheme with uniform theta and phi spacing
        """
        ...

    @staticmethod
    def interval(thetas:typing.Sequence[builtins.float], theta_spacings:typing.Sequence[builtins.float], phis:typing.Sequence[builtins.float], phi_spacings:typing.Sequence[builtins.float]) -> BinningScheme:
        r"""
        Create an interval binning scheme with variable spacing
        """
        ...

    @staticmethod
    def custom(bins:typing.Sequence[typing.Sequence[typing.Sequence[builtins.float]]]) -> BinningScheme:
        r"""
        Create a custom binning scheme with explicit bin edges
        Each bin is specified as [[theta_min, theta_max], [phi_min, phi_max]]
        """
        ...

    def thetas(self) -> builtins.list[builtins.float]:
        r"""
        Returns a list of all theta bin centre values
        """
        ...

    def phis(self) -> builtins.list[builtins.float]:
        r"""
        Returns a list of all phi bin centre values
        """
        ...

    def bins(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Returns all 2D bins as a numpy array of shape (n_bins, 2) with columns [theta, phi]
        """
        ...

    def bins_1d(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Returns unique 1D theta bins as a numpy array
        """
        ...

    def num_bins(self) -> builtins.int:
        r"""
        Returns the number of bins
        """
        ...


class Convergence:
    mean: Results
    sem: Results
    count: builtins.int
    max_orientations: builtins.int
    def __new__(cls,settings:Settings, geoms:typing.Optional[typing.Sequence[Geom]]=None): ...
    def solve(self) -> None:
        r"""
        Solve the multi-orientation scattering problem using work-stealing.
        Periodically checks for Python signals (Ctrl-C) and interrupts if needed.
        """
        ...

    def set_max_orientations(self, max_orientations:builtins.int) -> None:
        r"""
        Set the max orientations (safety cap).
        """
        ...

    def add_target(self, param:Param, relative_error:builtins.float) -> None:
        r"""
        Add a convergence target for a parameter (Python API).
        Solver terminates when ALL targets are satisfied.
        """
        ...

    def clear_targets(self) -> None:
        r"""
        Clear all convergence targets (Python API).
        """
        ...

    def py_reset(self) -> None:
        r"""
        Reset the solver to initial state.
        """
        ...

    def py_reset_sampler(self) -> None:
        r"""
        Reset the orientation sampler (for reproducibility).
        """
        ...

    def save(self, directory:typing.Optional[builtins.str]=None) -> None:
        r"""
        Save simulation results to disk.
        
        Writes Mueller matrices, parameters, and other output files to the
        specified directory (or the directory configured in settings).
        
        Args:
            directory: Optional output directory path. If not provided, uses
                       the directory from settings.
        """
        ...


class Euler:
    alpha: builtins.float
    beta: builtins.float
    gamma: builtins.float
    def __new__(cls,alpha:builtins.float, beta:builtins.float, gamma:builtins.float): ...
    def __repr__(self) -> builtins.str:
        ...


class Geom:
    first_shape_vertices: builtins.list[tuple[builtins.float, builtins.float, builtins.float]]
    def __new__(cls,shapes:typing.Sequence[Shape]): ...
    @staticmethod
    def from_file(filename:builtins.str) -> builtins.list[Geom]:
        ...


class MultiProblem:
    r"""
    Multi-orientation light scattering simulation for a single geometry.
    
    Computes orientation-averaged scattering properties by running multiple
    single-orientation simulations and averaging the results. Supports both
    random and systematic orientation sampling schemes. Results include
    Mueller matrices, cross-sections, and derived optical parameters.
    
    # Examples
    ```python
    import goad_py as goad
    
    # Create orientation scheme and settings
    orientations = goad.create_uniform_orientation(100)
    settings = goad.Settings("particle.obj", orientation=orientations)
    
    # Run multi-orientation simulation
    mp = goad.MultiProblem(settings)
    mp.py_solve()
    
    # Access averaged results
    results = mp.results
    print(f"Scattering cross-section: {results.scat_cross}")
    ```
    """
    results: Results
    num_orientations: builtins.int
    def __new__(cls,settings:Settings, geoms:typing.Optional[typing.Sequence[Geom]]=None): ...
    def solve(self) -> None:
        r"""
        Solve the multi-orientation scattering problem.
        
        Computes scattering properties averaged over all orientations using
        parallel processing. The Global Interpreter Lock (GIL) is released
        during computation to allow concurrent Python operations.
        
        # Returns
        PyResult<()> - Success or error if computation fails
        """
        ...

    def save(self, directory:typing.Optional[builtins.str]=None) -> None:
        r"""
        Save simulation results to disk.
        
        Writes Mueller matrices, parameters, and other output files to the
        specified directory (or the directory configured in settings).
        
        Args:
            directory: Optional output directory path. If not provided, uses
                       the directory from settings.
        """
        ...

    def py_reset(self) -> None:
        r"""
        Reset the multiproblem to initial state
        """
        ...

    def py_regenerate_orientations(self) -> None:
        r"""
        Regenerate orientations (useful for random schemes)
        """
        ...


class Orientation:
    scheme: Scheme
    euler_convention: EulerConvention
    @staticmethod
    def uniform(num_orients:builtins.int, euler_convention:typing.Optional[EulerConvention]=None) -> Orientation:
        ...

    @staticmethod
    def discrete(eulers:typing.Sequence[Euler], euler_convention:typing.Optional[EulerConvention]=None) -> Orientation:
        ...

    def __repr__(self) -> builtins.str:
        ...


class Problem:
    r"""
    A solvable physics problem.
    """
    settings: Settings
    geom: Geom
    results: Results
    def __new__(cls,settings:typing.Optional[Settings]=None, geom:typing.Optional[Geom]=None): ...
    def set_settings(self, settings:Settings) -> None:
        r"""
        Setter function for the problem settings
        """
        ...

    def py_solve(self) -> None:
        ...

    def py_print_stats(self) -> None:
        ...


class Results:
    r"""
    Complete results from a GOAD light scattering simulation.
    
    Contains all computed scattering data including Mueller matrices,
    amplitude matrices, power distributions, and derived parameters.
    Supports both 2D angular distributions and 1D integrated results.
    """
    ...

class Settings:
    r"""
    Runtime configuration for the application.
    """
    eulers: builtins.list[builtins.float]
    orientation: Orientation
    geom_path: builtins.str
    wavelength: builtins.float
    particle_refr_index_re: builtins.float
    particle_refr_index_im: builtins.float
    medium_refr_index_re: builtins.float
    medium_refr_index_im: builtins.float
    beam_power_threshold: builtins.float
    cutoff: builtins.float
    max_rec: builtins.int
    max_tir: builtins.int
    zones: builtins.list[ZoneConfig]
    geom_scale: typing.Optional[builtins.list[builtins.float]]
    seed: typing.Optional[builtins.int]
    distortion: typing.Optional[builtins.float]
    fov_factor: typing.Optional[builtins.float]
    quiet: builtins.bool
    def __new__(cls,geom_path:builtins.str, wavelength:builtins.float=0.5320000052452087, particle_refr_index_re:builtins.float=1.309999942779541, particle_refr_index_im:builtins.float=0.0, medium_refr_index_re:builtins.float=1.0, medium_refr_index_im:builtins.float=0.0, orientation:typing.Optional[Orientation]=None, zones:typing.Optional[typing.Sequence[ZoneConfig]]=None, beam_power_threshold:builtins.float=0.004999999888241291, beam_area_threshold_fac:builtins.float=0.10000000149011612, cutoff:builtins.float=0.9900000095367432, max_rec:builtins.int=10, max_tir:builtins.int=10, scale:builtins.float=1.0, distortion:typing.Optional[builtins.float]=None, directory:builtins.str='goad_run', mapping:Mapping=..., coherence:builtins.bool=True, quiet:builtins.bool=False, seed:typing.Optional[builtins.int]=None): ...
    def set_eulers(self, euler:typing.Sequence[builtins.float]) -> None:
        r"""
        Set the euler angles
        """
        ...

    def set_orientation(self, orientation:Orientation) -> None:
        r"""
        Set the full orientation object
        """
        ...

    def set_geom_path(self, geom_path:builtins.str) -> None:
        r"""
        Set the geometry file path
        """
        ...

    def set_wavelength(self, wavelength:builtins.float) -> None:
        r"""
        Set the wavelength
        """
        ...

    def set_particle_refr_index_re(self, re:builtins.float) -> None:
        r"""
        Set the particle refractive index (real part)
        """
        ...

    def set_particle_refr_index_im(self, im:builtins.float) -> None:
        r"""
        Set the particle refractive index (imaginary part)
        """
        ...

    def set_medium_refr_index_re(self, re:builtins.float) -> None:
        r"""
        Set the medium refractive index (real part)
        """
        ...

    def set_medium_refr_index_im(self, im:builtins.float) -> None:
        r"""
        Set the medium refractive index (imaginary part)
        """
        ...

    def set_beam_power_threshold(self, threshold:builtins.float) -> None:
        r"""
        Set the beam power threshold
        """
        ...

    def set_cutoff(self, cutoff:builtins.float) -> None:
        r"""
        Set the cutoff
        """
        ...

    def set_max_rec(self, max_rec:builtins.int) -> None:
        r"""
        Set the max recursion depth
        """
        ...

    def set_max_tir(self, max_tir:builtins.int) -> None:
        r"""
        Set the max TIR bounces
        """
        ...

    def set_zones(self, zones:typing.Sequence[ZoneConfig]) -> None:
        r"""
        Set the zones configuration
        """
        ...

    def set_geom_scale(self, geom_scale:typing.Optional[typing.Sequence[builtins.float]]) -> None:
        r"""
        Set the per-axis geometry scaling [x, y, z]
        """
        ...

    def set_seed(self, seed:typing.Optional[builtins.int]) -> None:
        r"""
        Set the seed for random number generation
        """
        ...

    def set_distortion(self, distortion:typing.Optional[builtins.float]) -> None:
        r"""
        Set the distortion factor
        """
        ...

    def set_fov_factor(self, fov_factor:typing.Optional[builtins.float]) -> None:
        r"""
        Set the field of view factor
        """
        ...

    def set_quiet(self, quiet:builtins.bool) -> None:
        r"""
        Set quiet mode (suppress progress bars)
        """
        ...


class Shape:
    r"""
    Represents a 3D surface mesh.
    """
    def __new__(cls,vertices:typing.Sequence[tuple[builtins.float, builtins.float, builtins.float]], face_indices:typing.Sequence[typing.Sequence[builtins.int]], id:builtins.int, refr_index_re:builtins.float, refr_index_im:builtins.float): ...
    ...

class Zone:
    r"""
    A zone represents a region of the scattering sphere with its own binning,
    results, and computed parameters.
    """
    label: typing.Optional[builtins.str]
    zone_type: ZoneType
    name: builtins.str
    num_bins: builtins.int
    bins: numpy.typing.NDArray[numpy.float32]
    mueller: numpy.typing.NDArray[numpy.float32]
    mueller_1d: typing.Optional[numpy.typing.NDArray[numpy.float32]]
    bins_1d: typing.Optional[numpy.typing.NDArray[numpy.float32]]
    params: typing.Any
    def __repr__(self) -> builtins.str:
        ...


class ZoneConfig:
    r"""
    Configuration for a zone, as specified in TOML or via CLI.
    """
    label: typing.Optional[builtins.str]
    binning: BinningScheme
    def __new__(cls,binning:BinningScheme, label:typing.Optional[builtins.str]=None): ...
    def set_label(self, label:typing.Optional[builtins.str]) -> None:
        r"""
        Set the zone label
        """
        ...

    def set_binning(self, binning:BinningScheme) -> None:
        r"""
        Set the binning scheme
        """
        ...

    def __repr__(self) -> builtins.str:
        ...


class Zones:
    r"""
    A collection of zones for a simulation.
    """
    full: typing.Optional[Zone]
    forward: typing.Optional[Zone]
    backward: typing.Optional[Zone]
    all_zones: builtins.list[Zone]
    def __len__(self) -> builtins.int:
        r"""
        Get the number of zones
        """
        ...

    def __getitem__(self, index:builtins.int) -> Zone:
        r"""
        Get a zone by index
        """
        ...

    def get(self, label:builtins.str) -> typing.Optional[Zone]:
        r"""
        Get a zone by label
        """
        ...

    def get_by_type(self, zone_type:ZoneType) -> typing.Optional[Zone]:
        r"""
        Get a zone by type (returns first matching zone)
        """
        ...

    def __repr__(self) -> builtins.str:
        ...

    def __iter__(self) -> ZonesIterator:
        ...


class ZonesIterator:
    r"""
    Iterator for Zones in Python
    """
    def __iter__(self) -> ZonesIterator:
        ...

    def __next__(self) -> typing.Optional[Zone]:
        ...


class EulerConvention(Enum):
    r"""
    Euler angle order for the discrete orientation scheme.
    """
    XZX = auto()
    XYX = auto()
    YXY = auto()
    YZY = auto()
    ZYZ = auto()
    ZXZ = auto()
    XZY = auto()
    XYZ = auto()
    YXZ = auto()
    YZX = auto()
    ZYX = auto()
    ZXY = auto()

class Mapping(Enum):
    r"""
    Enum representing different mapping methods from near to far field.
    """
    GeometricOptics = auto()
    ApertureDiffraction = auto()

class Param(Enum):
    Asymmetry = auto()
    Albedo = auto()
    ScatCross = auto()
    ExtCross = auto()
    BackscatterCross = auto()
    LidarRatio = auto()
    DepolarizationRatio = auto()
    BackscatterS11S22 = auto()
    ExtCrossOpticalTheorem = auto()

class Scheme(Enum):
    Uniform = auto()
    Discrete = auto()

class ZoneType(Enum):
    r"""
    The type of zone, which determines what parameters can be computed.
    """
    Full = auto()
    Forward = auto()
    Backward = auto()
    Custom = auto()

def create_discrete_orientation(eulers:typing.Sequence[Euler], euler_convention:typing.Optional[EulerConvention]=None) -> Orientation:
    r"""
    Create an Orientation with discrete scheme and default convention
    """
    ...

def create_uniform_orientation(num_orients:builtins.int, euler_convention:typing.Optional[EulerConvention]=None) -> Orientation:
    r"""
    Create an Orientation with uniform scheme and default convention
    """
    ...

def discrete_orientation(eulers:typing.Sequence[Euler]) -> Scheme:
    r"""
    Create a discrete orientation scheme from a list of Euler angles
    """
    ...

def sum_as_string(a:builtins.int, b:builtins.int) -> builtins.str:
    r"""
    Formats the sum of two numbers as string.
    """
    ...

def uniform_orientation(num_orients:builtins.int) -> Scheme:
    r"""
    Create a uniform orientation scheme with specified number of orientations
    """
    ...

