wavelength = 0.266
medium_refr_index = [1.0,0.0]
particle_refr_index = [[1.31,0.0]]
geom_name = "./examples/data/hex.obj"
beam_power_threshold = 0.005
beam_area_threshold_fac = 1 
total_power_cutoff = 0.99
max_rec = 10
max_tir = 10
far_field_resolution = 180

[[orientation]]
#Discrete = { alphas = [182], betas = [20], gammas = [20]}
Uniform = { num_orients = 25000}