wavelength = 0.532
medium_refr_index = [1.0,0.0]
particle_refr_index = [[1.31,0.0]]
geom_name = "./examples/data/hex.obj"
beam_power_threshold = 0.005
beam_area_threshold_fac = 1 
total_power_cutoff = 0.99
max_rec = 10
max_tir = 10

[binning]
#Simple = { num_theta = 100, num_phi = 120 }
#Interval = { thetas = [0,180], theta_spacings = [1], phis = [0,360], phi_spacings = [2]}
#Custom = { bins = [[0,0],[0,40],[20,180]] }

[[orientation]]
Discrete = { eulers = [[0,0,0]] }
#Uniform = { num_orients = 2 }